# Generated by Django 5.2.1 on 2025-06-07 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttestresult',
            name='test_launch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.testlaunch'),
            preserve_default=False,
        ),
    ]
