# Generated by Django 5.2.1 on 2025-06-07 06:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_studenttestresult_test_launch'),
    ]

    operations = [
        migrations.AddField(
            model_name='testlaunch',
            name='session_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='testlaunch',
            name='launched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
