# Generated by Django 5.2.1 on 2025-06-07 06:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_testlaunch_session_id_alter_testlaunch_launched_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testlaunch',
            name='session_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
