# Generated by Django 5.2.1 on 2025-06-07 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_testlaunch_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testlaunch',
            name='students',
        ),
    ]
