# Generated by Django 5.2.1 on 2025-06-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_testlaunch_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('one', 'Один ответ'), ('multiple', 'Несколько ответов'), ('true_false', 'Правда/Лож')], max_length=10),
        ),
    ]
