# Generated by Django 5.2.1 on 2025-06-07 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_question_question_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentanswer',
            name='text_answer',
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='test_launch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.testlaunch'),
            preserve_default=False,
        ),
    ]
