# Generated by Django 5.2.1 on 2025-06-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_studentanswer_text_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('one', 'Один ответ'), ('multiple', 'Несколько ответов'), ('true_false', 'Правда/Ложь')], max_length=10),
        ),
    ]
