# Generated by Django 5.2.1 on 2025-06-16 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='testlaunch',
            name='title',
            field=models.CharField(default='Без названия', help_text='Название для идентификации сессии', max_length=255, verbose_name='Название сессии'),
        ),
    ]
