# Generated by Django 5.2.1 on 2025-06-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_testlaunch_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testlaunch',
            name='title',
            field=models.CharField(help_text='Название для идентификации сессии', max_length=255, verbose_name='Название сессии'),
        ),
    ]
